version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeepertest
    ports:
      - "2181:2181"
    networks:
      - kafka-test

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafkatest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - kafka-test

networks:
  kafka-test:
    driver: bridge
